name: Salesforce Unlocked Package Validation and Deployment with SonarCloud security check
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    env:
      SFDX_DEFAULTDEVHUBUSERNAME: ${{ secrets.SFDX_DEFAULTDEVHUBUSERNAME }}
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_PROJECT_NAME: 'Github Action Sonar Cloud'
      SONAR_PROJECT_VERSION: '1.0'
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Install Node JS
      uses: actions/setup-node@v3
      with:
          node-version: 18

    - name: Install SFDX CLI
      run: |
          npm install @salesforce/cli --global
          echo sf version
          sf --version
 
    - name: Authenticate with DevHub
      run: sf org login sfdx-url --sfdx-url-file files/sfdx-auth-prod
    
    - name: Create Salesforce Unlocked package
      run: sfdx force:package:version:create -p DemoPackage -d force-app -w 10 --codecoverage --wait 10
 
    - name: Static Code Analysis with SonarQube
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ./force-app
        args: >
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.organization=rishiibagekar
          -Dsonar.sources=src
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Run SonarCloud analysis
      run: sonar-scanner
 
    - name: Install Salesforce Unlocked package
      run: sfdx force:package:install --package DemoPackage --wait 10 -r

    - name: Workflow succeeded
      run: echo "Workflow succeded"